---
- name: Set up Jenkins on EC2 instance
  hosts: jenkins
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins apt repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian binary/'
        state: present

    - name: Update apt package list after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Clone GitHub repository
      git:
        repo: 'https://github.com/spring-projects/spring-petclinic'
        dest: /home/ubuntu/myapp

    - name: Install kubectl
      shell: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl
